<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-leo0nel09/blob/main/ago11-12/miprimernotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

lista1=["hola", 2, 2.11]
print(lista1)

In [16]:
lista2=["kevin", 3]
x=lista1


['hola', 2.11]


In [17]:
print(x)

['hola', 2.11]


In [21]:
lista1.append("yepez")
print(lista1)
lista1.insert(2,"hola")
lista1

['hola', 2.11, 'mamita', 'yepez', 'yepez', 'yepez', 'yepez']


['hola', 2.11, 'mamita', 'mamita', 'yepez', 'yepez', 'yepez', 'yepez']

In [25]:
for i in lista1:
  print(i)


hola
2.11
mamita
mamita
yepez
yepez
yepez
yepez
Object `len(lista1)` not found.


In [ ]:
for i in range(len(lista1)):
  print(lista[i])

In [29]:
for i, item in enumerate(lista1):
  print(i, item)

0 hola
1 2.11
2 mamita
3 mamita
4 yepez
5 yepez
6 yepez
7 yepez


In [37]:
import numpy as np
arreglo=np.array([[1,2,3],[3,2,1]])
print(arreglo)


[[1 2 3]
 [3 2 1]]


In [42]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1*arr2)

[ 4 10 18]
